# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=16000']
    -   id: check-toml
    -   id: check-yaml
- repo: local
  hooks:
    - id: ruff-check
      name: Run ruff check
      entry: ruff check src/
      language: system
      types_or: [ python, pyi, jupyter, pyproject ]
    - id: ruff-format
      name: Run ruff format
      entry: ruff format src/
      language: system
      types_or: [ python, pyi, jupyter ]
    - id: mypy
      name: mypy
      language: system
      types: [python]
      entry: mypy
    - id: uv-build
      name: uv-build
      language: script
      entry: .pre-commit-scripts/build-check
