[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.12.0,<0.13"]

[project]
name = "mergeron"
version = "2026.739867.0"
description = "Python for analyzing merger enforcement policy"
readme = "README.rst"
keywords = [
  "concentration standards",
  "diversion ratio",
  "enforcement presumptions",
  "GUPPI",
  "merger enforcement policy",
  "merger guidelines",
  "merger screening",
  "upward pricing pressure",
]
license = "BSD-3-Clause"
license-files = [ "docs/source/license.rst" ]
authors = [ { name = "Murthy Kambhampaty", email = "smk@capeconomics.com" } ]
requires-python = ">=3.12,<4.0"
# Classifiers list: https://pypi.org/classifiers/
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
  "aenum",
  "attrs",
  "backports-zstd; python_version<'3.14'",
  "beautifulsoup4",
  "certifi",
  "h5py",
  "hdf5plugin",
  "jinja2",
  "joblib",
  "kdepy",
  "lxml",
  "matplotlib",
  "mpmath",
  "numpy",
  "pypdf",
  "python-calamine",
  "ruamel-yaml",
  "scipy",
  "sympy",
  "types-beautifulsoup4",
  "urllib3",
]
urls.Homepage = "https://software.capeconomics.com/mergeron"
urls.Repository = "https://github.com/capeconomics/mergeron.git"

[dependency-groups]
dev = [ "prek", "semver", ]
test = [
  "coverage",
  "pendulum",
  "pytest",
  "pytest-cache",
  "pytest-cov",
  "pytest-sugar",
  "pytest-xdist",
  "tox",
]
doc = [
  "ipython",
  "ipython-pygments-lexers",
  "linuxdoc",
  "roman-numerals",
  "sphinx",
  "sphinx-autoapi",
  "sphinx-autodoc-typehints",
  "sphinx-immaterial",
]
lint = [
 "mypy",
 "ruff",
]

[tool.mypy]
ignore_missing_imports = false
warn_redundant_casts = true
warn_unreachable = true
allow_redefinition_new = true
local_partial_types = true
disable_error_code = [ "import-untyped" ]
strict_equality = true
strict_equality_for_none = true
strict = true
pretty = true
cache_fine_grained = true
enable_incomplete_feature = [ "PreciseTupleTypes" ]
fixed_format_cache = true
no_implicit_optional = true
no_implicit_reexport = false

[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4
# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
]
fix = true

[tool.ruff.format]
preview = true
indent-style = "space"
quote-style = "double"
line-ending = "lf"
skip-magic-trailing-comma = true
docstring-code-line-length = 60
docstring-code-format = true

[tool.ruff.lint]
preview = true
# Borrowed or adapted primarily from,
#   https://github.com/sphinx-doc/sphinx/blob/master/pyproject.toml
select = [
  # plugins:
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "D",    # docstrings
  "E",    # pycodestyle
  "F",    # Pyflakes
  "FURB", # refurb
  "I",    # isort
  "ICN",  # flake8-import-conventions
  "NPY",  # NumPy-specific rules
  "PIE",  # flake8-pie
  "PL",   # pylint
  "PTH",  # flake8-use-pathlib
  "RUF",  # ruff-specific
  "S",    # flake8-bandit
  "SIM",  # flake8-simplify
  "TC",   # flake8-type-checking
  "TID",  # flake8-tidy-imports
  "UP",   # pyupgrade
  "W",    # pycodestyle
]
extend-select = ["ANN", "PYI"]
ignore = [
  # flake8-bugbear
  "function-uses-loop-variable",
  # flake-8,
  "line-too-long",    # line length managed per Black formatter rules, ignore tis
  "unnecessary-dunder-call", # dunder calls
  # flake8-comprehensions
  "magic-value-comparison", # an occasional comarison to scalar is unavoidable
  "bad-dunder-method-name", # dunder method ... has no special meaning in Python 3
  # RUF
  "ambiguous-unicode-character-docstring",
  "ambiguous-unicode-character-comment",
  "non-empty-init-module",  # we define package/subpackage types and constants in __init__.py files
  "rule-codes-in-suppression-comments",  # rule codes are harder to read but more compact; lookup not too hard
  "suspicious-subprocess-import",    # accept subprocess module
  # flake8-type-checking
  "relative-imports",  # we use relative imports - repeated patterns, flexible to name-changes
  # pyupgrade
  "non-pep695-type-alias",   # prefer typing.TypeAlias to type keyword due to inconvenience with latter
]
# names with leading underscore for positional arguments and parametric variables (no reassigment)
dummy-variable-rgx = "^_+$"

isort.force-single-line = true
pydocstyle.convention = "numpy"

pylint.max-args = 16
pylint.max-branches = 16
pylint.max-locals = 32
pylint.max-statements = 80

# We define package/subpackage types and constants in __init__.py files.
ruff.strictly-empty-init-modules = false

[tool.pytest.ini_options]
testpaths = [ "tests" ]
addopts = [
  "--import-mode=importlib",
  "--cov=mergeron",
  "--cov-report=html:tests/cov_html",
]
filterwarnings = [
  "all",
  "ignore::DeprecationWarning:dateutil.tz.tz",
  "ignore::DeprecationWarning:jinja2.lexer",
  "ignore::DeprecationWarning:joblib._utils",
  "ignore::RuntimeWarning:mergeron.core.empirical_margin_distribution",
  "ignore::RuntimeWarning:mergeron.core.proportions_tests",
  "ignore::RuntimeWarning:mergeron.gen.data_generation_functions",
  "ignore::RuntimeWarning:mergeron.gen.enforcement_stats",
  "ignore::RuntimeWarning:mergeron.gen.upp_tests",
]
log_auto_indent = "4"
tmp_path_retention_policy = "failed"

[tool.tox]
isolated_build = true

[tool.tox.env_run_base]
allowlist_externals = [ "uv", "uv_build", "pytest" ]
commands = [
  [
    "uv",
    "sync",
    "--active",
    "--group",
    "test",
  ],
  [
    "pytest",
    { replace = "posargs", extend = true },
  ],
]
description = "install pytest in a virtual environment and invoke"
package = "wheel"
wheel_build_env = ".pkg"

[tool.ty.rules]
all = "ignore"

[tool.uv]
default-groups = [ "dev" ]

[tool.uv.pip]
no-build = true

[tool.uv_build]
src-layout = true
