name: Documentation

on:
  push:
    branches:
      - trunk

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          version: "latest-known"
          activate-environment: true
          enable-cache: false

      - name: Install dependencies
        run: |
          uv sync --group doc --no-install-project

      - name: Build with Sphinx
        run: |
          sphinx-build -b html -a docs/source/ docs/build/mergeron

      # Deploy to Cloudflare
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            deploy --name mergeron --assets ./docs/build --compatibility-date 2026-08-13

# vim: noai:ts=2:sw=2
